Kaatru IIT Madras

Candidate: Ramaseshan M S

Goal:
Develop a model to find the variables that are significant in the demand for shared bikes with the available independent variables and report appropriate metrics of your model evaluation.

Plan: Use Lasso Regression model to identify the significant parameters.

In [ ]:
#Importing Necessary libraries
import pandas as pd
import numpy as np

In [2]:
#Upload the Dataset
dataset = pd.read_csv('day.csv')
dataset

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [38]:
dataset.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.995890,0.690411,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.000339,0.462641,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [7]:
dataset.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

Dataset does not have any null values nor any categorical variables except the date-time variable

In [8]:
#Splitting independent and dependent variables
x= dataset.iloc[:,:-1]
y= dataset.iloc[:,-1]

In [11]:
x

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290

In [19]:
#Splitting date time variable into three separate columns and removing the original column from x

x['Year'] = x['dteday'].apply(lambda date: date.split('-')[2])

x['Month'] = x['dteday'].apply(lambda date: date.split('-')[1])

x['Day'] = x['dteday'].apply(lambda date: date.split('-')[0])

In [20]:
x

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,Year,Month,Day
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,2018,01,01
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,2018,01,02
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,2018,01,03
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,2018,01,04
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,2018,01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2019,12,27
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,2019,12,28
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,2019,12,29
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,2019,12,30
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2019,12,31

In [22]:
del x['dteday']

In [23]:
x

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,Year,Month,Day
0,1,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,2018,01,01
1,2,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,2018,01,02
2,3,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,2018,01,03
3,4,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,2018,01,04
4,5,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,2018,01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2019,12,27
726,727,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,2019,12,28
727,728,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,2019,12,29
728,729,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,2019,12,30
729,730,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2019,12,31

After Preprocessing we are proceeding to Lasso Regression models. Note we have not scaled down the variables in preprocessing.

In [24]:
#importing necessary libraries
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso

In [25]:
#Splitting dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [26]:
#Applying scaling with Lasso model
pipeline = Pipeline([
                     ('scaler',StandardScaler()),
                     ('model',Lasso())
])

In [27]:
#Now we are proceeding to find the alpha variable. Lets try a range of 0.1 to 10
search = GridSearchCV(pipeline,
                      {'model__alpha':np.arange(0.1,10,0.1)},
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )

In [29]:
#Fitting the model
search.fit(x_train,y_train)

Fitting 5 folds for each of 99 candidates, totalling 495 fits
[CV 1/5] END .................model__alpha=0.1;, score=-7.559 total time=   0.0s
[CV 2/5] END .................model__alpha=0.1;, score=-5.277 total time=   0.0s
[CV 3/5] END .................model__alpha=0.1;, score=-5.934 total time=   0.0s
[CV 4/5] END .................model__alpha=0.1;, score=-6.359 total time=   0.0s
[CV 5/5] END .................model__alpha=0.1;, score=-6.628 total time=   0.0s
[CV 1/5] END .................model__alpha=0.2;, score=-4.334 total time=   0.0s

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.901e+05, tolerance: 1.432e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.906e+05, tolerance: 1.500e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.880e+05, tolerance: 1.413e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.930e+05, tolerance: 1.496e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.874e+05, tolerance: 1.447e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.366e+05, tolerance: 1.432e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.428e+05, tolerance: 1.500e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

[CV 2/5] END .................model__alpha=0.2;, score=-3.007 total time=   0.0s
[CV 3/5] END .................model__alpha=0.2;, score=-3.561 total time=   0.0s
[CV 4/5] END .................model__alpha=0.2;, score=-3.562 total time=   0.0s
[CV 5/5] END .................model__alpha=0.2;, score=-3.859 total time=   0.0s
[CV 1/5] END .model__alpha=0.30000000000000004;, score=-2.167 total time=   0.0s
[CV 2/5] END .model__alpha=0.30000000000000004;, score=-1.460 total time=   0.0s
[CV 3/5] END .model__alpha=0.30000000000000004;, score=-1.926 total time=   0.0s
[CV 4/5] END .model__alpha=0.30000000000000004;, score=-1.790 total time=   0.0s

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.380e+05, tolerance: 1.413e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.475e+05, tolerance: 1.496e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.366e+05, tolerance: 1.447e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.381e+05, tolerance: 1.432e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.476e+05, tolerance: 1.500e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.401e+05, tolerance: 1.413e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.541e+05, tolerance: 1.496e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.379e+05, tolerance: 1.447e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

[CV 5/5] END .model__alpha=0.30000000000000004;, score=-1.978 total time=   0.0s
[CV 1/5] END .................model__alpha=0.4;, score=-1.050 total time=   0.0s
[CV 2/5] END .................model__alpha=0.4;, score=-0.803 total time=   0.0s
[CV 3/5] END .................model__alpha=0.4;, score=-1.079 total time=   0.0s
[CV 4/5] END .................model__alpha=0.4;, score=-0.892 total time=   0.0s
[CV 5/5] END .................model__alpha=0.4;, score=-1.014 total time=   0.0s
[CV 1/5] END .................model__alpha=0.5;, score=-0.391 total time=   0.0s
[CV 2/5] END .................model__alpha=0.5;, score=-0.428 total time=   0.0s

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.961e+05, tolerance: 1.432e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.089e+05, tolerance: 1.500e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.985e+05, tolerance: 1.413e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.169e+05, tolerance: 1.496e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.956e+05, tolerance: 1.447e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.071e+05, tolerance: 1.432e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.153e+05, tolerance: 1.500e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.142e+05, tolerance: 1.413e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

[CV 3/5] END .................model__alpha=0.5;, score=-0.426 total time=   0.0s
[CV 4/5] END .................model__alpha=0.5;, score=-0.492 total time=   0.0s
[CV 5/5] END .................model__alpha=0.5;, score=-0.389 total time=   0.0s
[CV 1/5] END .................model__alpha=0.6;, score=-0.616 total time=   0.0s
[CV 2/5] END .................model__alpha=0.6;, score=-0.465 total time=   0.0s
[CV 3/5] END .................model__alpha=0.6;, score=-0.550 total time=   0.0s
[CV 4/5] END .................model__alpha=0.6;, score=-0.534 total time=   0.0s
[CV 5/5] END .................model__alpha=0.6;, score=-0.535 total time=   0.0s

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.480e+05, tolerance: 1.496e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.133e+05, tolerance: 1.447e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

[CV 1/5] END ..model__alpha=0.7000000000000001;, score=-0.797 total time=   0.0s
[CV 2/5] END ..model__alpha=0.7000000000000001;, score=-0.633 total time=   0.0s
[CV 3/5] END ..model__alpha=0.7000000000000001;, score=-0.782 total time=   0.0s
[CV 4/5] END ..model__alpha=0.7000000000000001;, score=-0.738 total time=   0.0s
[CV 5/5] END ..model__alpha=0.7000000000000001;, score=-0.728 total time=   0.0s
[CV 1/5] END .................model__alpha=0.8;, score=-1.040 total time=   0.0s
[CV 2/5] END .................model__alpha=0.8;, score=-0.826 total time=   0.0s
[CV 3/5] END .................model__alpha=0.8;, score=-0.977 total time=   0.0s
[CV 4/5] END .................model__alpha=0.8;, score=-0.946 total time=   0.0s
[CV 5/5] END .................model__alpha=0.8;, score=-0.951 total time=   0.0s
[CV 1/5] END .................model__alpha=0.9;, score=-1.317 total time=   0.0s
[CV 2/5] END .................model__alpha=0.9;, score=-1.063 total time=   0.0s
[CV 3/5] END .................model__alpha=0.9;, score=-1.237 total time=   0.0s
[CV 4/5] END .................model__alpha=0.9;, score=-1.202 total time=   0.0s
[CV 5/5] END .................model__alpha=0.9;, score=-1.204 total time=   0.0s
[CV 1/5] END .................model__alpha=1.0;, score=-1.626 total time=   0.0s
[CV 2/5] END .................model__alpha=1.0;, score=-1.291 total time=   0.0s
[CV 3/5] END .................model__alpha=1.0;, score=-1.528 total time=   0.0s
[CV 4/5] END .................model__alpha=1.0;, score=-1.468 total time=   0.0s
[CV 5/5] END .................model__alpha=1.0;, score=-1.485 total time=   0.0s
[CV 1/5] END .................model__alpha=1.1;, score=-1.955 total time=   0.0s
[CV 2/5] END .................model__alpha=1.1;, score=-1.562 total time=   0.0s
[CV 3/5] END .................model__alpha=1.1;, score=-1.848 total time=   0.0s
[CV 4/5] END .................model__alpha=1.1;, score=-1.795 total time=   0.0s
[CV 5/5] END .................model__alpha=1.1;, score=-1.798 total time=   0.0s
[CV 1/5] END ..model__alpha=1.2000000000000002;, score=-2.341 total time=   0.0s
[CV 2/5] END ..model__alpha=1.2000000000000002;, score=-1.859 total time=   0.0s
[CV 3/5] END ..model__alpha=1.2000000000000002;, score=-2.200 total time=   0.0s
[CV 4/5] END ..model__alpha=1.2000000000000002;, score=-2.136 total time=   0.0s
[CV 5/5] END ..model__alpha=1.2000000000000002;, score=-2.140 total time=   0.0s
[CV 1/5] END ..model__alpha=1.3000000000000003;, score=-2.704 total time=   0.0s
[CV 2/5] END ..model__alpha=1.3000000000000003;, score=-2.159 total time=   0.0s
[CV 3/5] END ..model__alpha=1.3000000000000003;, score=-2.582 total time=   0.0s
[CV 4/5] END ..model__alpha=1.3000000000000003;, score=-2.507 total time=   0.0s
[CV 5/5] END ..model__alpha=1.3000000000000003;, score=-2.475 total time=   0.0s
[CV 1/5] END ..model__alpha=1.4000000000000001;, score=-3.135 total time=   0.0s
[CV 2/5] END ..model__alpha=1.4000000000000001;, score=-2.531 total time=   0.0s
[CV 3/5] END ..model__alpha=1.4000000000000001;, score=-2.967 total time=   0.0s
[CV 4/5] END ..model__alpha=1.4000000000000001;, score=-2.843 total time=   0.0s
[CV 5/5] END ..model__alpha=1.4000000000000001;, score=-2.871 total time=   0.0s
[CV 1/5] END ..model__alpha=1.5000000000000002;, score=-3.599 total time=   0.0s
[CV 2/5] END ..model__alpha=1.5000000000000002;, score=-2.858 total time=   0.0s
[CV 3/5] END ..model__alpha=1.5000000000000002;, score=-3.405 total time=   0.0s
[CV 4/5] END ..model__alpha=1.5000000000000002;, score=-3.263 total time=   0.0s
[CV 5/5] END ..model__alpha=1.5000000000000002;, score=-3.317 total time=   0.0s
[CV 1/5] END .................model__alpha=1.6;, score=-4.095 total time=   0.0s
[CV 2/5] END .................model__alpha=1.6;, score=-3.251 total time=   0.0s
[CV 3/5] END .................model__alpha=1.6;, score=-3.875 total time=   0.0s
[CV 4/5] END .................model__alpha=1.6;, score=-3.851 total time=   0.0s
[CV 5/5] END .................model__alpha=1.6;, score=-3.749 total time=   0.0s
[CV 1/5] END ..model__alpha=1.7000000000000002;, score=-4.623 total time=   0.0s
[CV 2/5] END ..model__alpha=1.7000000000000002;, score=-3.671 total time=   0.0s
[CV 3/5] END ..model__alpha=1.7000000000000002;, score=-4.374 total time=   0.0s
[CV 4/5] END ..model__alpha=1.7000000000000002;, score=-4.192 total time=   0.0s
[CV 5/5] END ..model__alpha=1.7000000000000002;, score=-4.233 total time=   0.0s
[CV 1/5] END ..model__alpha=1.8000000000000003;, score=-5.183 total time=   0.0s
[CV 2/5] END ..model__alpha=1.8000000000000003;, score=-4.115 total time=   0.0s
[CV 3/5] END ..model__alpha=1.8000000000000003;, score=-4.904 total time=   0.0s
[CV 4/5] END ..model__alpha=1.8000000000000003;, score=-4.699 total time=   0.0s
[CV 5/5] END ..model__alpha=1.8000000000000003;, score=-4.765 total time=   0.0s
[CV 1/5] END ..model__alpha=1.9000000000000001;, score=-5.802 total time=   0.0s
[CV 2/5] END ..model__alpha=1.9000000000000001;, score=-4.585 total time=   0.0s
[CV 3/5] END ..model__alpha=1.9000000000000001;, score=-5.464 total time=   0.0s
[CV 4/5] END ..model__alpha=1.9000000000000001;, score=-5.275 total time=   0.0s
[CV 5/5] END ..model__alpha=1.9000000000000001;, score=-5.306 total time=   0.0s
[CV 1/5] END .................model__alpha=2.0;, score=-6.399 total time=   0.0s
[CV 2/5] END .................model__alpha=2.0;, score=-5.080 total time=   0.0s
[CV 3/5] END .................model__alpha=2.0;, score=-6.051 total time=   0.0s
[CV 4/5] END .................model__alpha=2.0;, score=-5.801 total time=   0.0s
[CV 5/5] END .................model__alpha=2.0;, score=-5.858 total time=   0.0s
[CV 1/5] END .................model__alpha=2.1;, score=-7.055 total time=   0.0s
[CV 2/5] END .................model__alpha=2.1;, score=-5.601 total time=   0.0s
[CV 3/5] END .................model__alpha=2.1;, score=-6.675 total time=   0.0s
[CV 4/5] END .................model__alpha=2.1;, score=-6.389 total time=   0.0s
[CV 5/5] END .................model__alpha=2.1;, score=-6.459 total time=   0.0s
[CV 1/5] END .................model__alpha=2.2;, score=-7.743 total time=   0.0s
[CV 2/5] END .................model__alpha=2.2;, score=-6.143 total time=   0.0s
[CV 3/5] END .................model__alpha=2.2;, score=-7.325 total time=   0.0s
[CV 4/5] END .................model__alpha=2.2;, score=-7.020 total time=   0.0s
[CV 5/5] END .................model__alpha=2.2;, score=-7.084 total time=   0.0s
[CV 1/5] END ..model__alpha=2.3000000000000003;, score=-8.463 total time=   0.0s
[CV 2/5] END ..model__alpha=2.3000000000000003;, score=-6.719 total time=   0.0s
[CV 3/5] END ..model__alpha=2.3000000000000003;, score=-8.007 total time=   0.0s
[CV 4/5] END ..model__alpha=2.3000000000000003;, score=-7.676 total time=   0.0s
[CV 5/5] END ..model__alpha=2.3000000000000003;, score=-7.775 total time=   0.0s
[CV 1/5] END ..model__alpha=2.4000000000000004;, score=-9.206 total time=   0.0s
[CV 2/5] END ..model__alpha=2.4000000000000004;, score=-7.316 total time=   0.0s
[CV 3/5] END ..model__alpha=2.4000000000000004;, score=-8.718 total time=   0.0s
[CV 4/5] END ..model__alpha=2.4000000000000004;, score=-8.352 total time=   0.0s
[CV 5/5] END ..model__alpha=2.4000000000000004;, score=-8.436 total time=   0.0s
[CV 1/5] END ..model__alpha=2.5000000000000004;, score=-9.998 total time=   0.0s
[CV 2/5] END ..model__alpha=2.5000000000000004;, score=-7.978 total time=   0.0s
[CV 3/5] END ..model__alpha=2.5000000000000004;, score=-9.460 total time=   0.0s
[CV 4/5] END ..model__alpha=2.5000000000000004;, score=-9.065 total time=   0.0s
[CV 5/5] END ..model__alpha=2.5000000000000004;, score=-9.147 total time=   0.0s
[CV 1/5] END ................model__alpha=2.6;, score=-10.814 total time=   0.0s
[CV 2/5] END .................model__alpha=2.6;, score=-8.574 total time=   0.0s
[CV 3/5] END ................model__alpha=2.6;, score=-10.231 total time=   0.0s
[CV 4/5] END .................model__alpha=2.6;, score=-9.876 total time=   0.0s
[CV 5/5] END .................model__alpha=2.6;, score=-9.900 total time=   0.0s
[CV 1/5] END ................model__alpha=2.7;, score=-11.662 total time=   0.0s
[CV 2/5] END .................model__alpha=2.7;, score=-9.259 total time=   0.0s
[CV 3/5] END ................model__alpha=2.7;, score=-11.034 total time=   0.0s
[CV 4/5] END ................model__alpha=2.7;, score=-10.573 total time=   0.0s
[CV 5/5] END ................model__alpha=2.7;, score=-10.678 total time=   0.0s
[CV 1/5] END .model__alpha=2.8000000000000003;, score=-12.542 total time=   0.0s
[CV 2/5] END ..model__alpha=2.8000000000000003;, score=-9.958 total time=   0.0s
[CV 3/5] END .model__alpha=2.8000000000000003;, score=-11.866 total time=   0.0s
[CV 4/5] END .model__alpha=2.8000000000000003;, score=-11.371 total time=   0.0s
[CV 5/5] END .model__alpha=2.8000000000000003;, score=-11.474 total time=   0.0s
[CV 1/5] END .model__alpha=2.9000000000000004;, score=-13.454 total time=   0.0s
[CV 2/5] END .model__alpha=2.9000000000000004;, score=-10.682 total time=   0.0s
[CV 3/5] END .model__alpha=2.9000000000000004;, score=-12.729 total time=   0.0s
[CV 4/5] END .model__alpha=2.9000000000000004;, score=-12.198 total time=   0.0s
[CV 5/5] END .model__alpha=2.9000000000000004;, score=-12.317 total time=   0.0s
[CV 1/5] END .model__alpha=3.0000000000000004;, score=-14.398 total time=   0.0s
[CV 2/5] END .model__alpha=3.0000000000000004;, score=-11.431 total time=   0.0s
[CV 3/5] END .model__alpha=3.0000000000000004;, score=-13.622 total time=   0.0s
[CV 4/5] END .model__alpha=3.0000000000000004;, score=-13.053 total time=   0.0s
[CV 5/5] END .model__alpha=3.0000000000000004;, score=-13.181 total time=   0.0s
[CV 1/5] END ................model__alpha=3.1;, score=-15.398 total time=   0.0s
[CV 2/5] END ................model__alpha=3.1;, score=-12.206 total time=   0.0s
[CV 3/5] END ................model__alpha=3.1;, score=-14.545 total time=   0.0s
[CV 4/5] END ................model__alpha=3.1;, score=-13.938 total time=   0.0s
[CV 5/5] END ................model__alpha=3.1;, score=-14.075 total time=   0.0s
[CV 1/5] END ................model__alpha=3.2;, score=-16.381 total time=   0.0s
[CV 2/5] END ................model__alpha=3.2;, score=-13.006 total time=   0.0s
[CV 3/5] END ................model__alpha=3.2;, score=-15.498 total time=   0.0s
[CV 4/5] END ................model__alpha=3.2;, score=-14.852 total time=   0.0s
[CV 5/5] END ................model__alpha=3.2;, score=-14.994 total time=   0.0s
[CV 1/5] END .model__alpha=3.3000000000000003;, score=-17.441 total time=   0.0s
[CV 2/5] END .model__alpha=3.3000000000000003;, score=-13.831 total time=   0.0s
[CV 3/5] END .model__alpha=3.3000000000000003;, score=-16.482 total time=   0.0s
[CV 4/5] END .model__alpha=3.3000000000000003;, score=-15.795 total time=   0.0s
[CV 5/5] END .model__alpha=3.3000000000000003;, score=-15.950 total time=   0.0s
[CV 1/5] END .model__alpha=3.4000000000000004;, score=-18.493 total time=   0.0s
[CV 2/5] END .model__alpha=3.4000000000000004;, score=-14.675 total time=   0.0s
[CV 3/5] END .model__alpha=3.4000000000000004;, score=-17.489 total time=   0.0s
[CV 4/5] END .model__alpha=3.4000000000000004;, score=-16.766 total time=   0.0s
[CV 5/5] END .model__alpha=3.4000000000000004;, score=-16.931 total time=   0.0s
[CV 1/5] END .model__alpha=3.5000000000000004;, score=-19.572 total time=   0.0s
[CV 2/5] END .model__alpha=3.5000000000000004;, score=-15.559 total time=   0.0s
[CV 3/5] END .model__alpha=3.5000000000000004;, score=-18.541 total time=   0.0s
[CV 4/5] END .model__alpha=3.5000000000000004;, score=-17.835 total time=   0.0s
[CV 5/5] END .model__alpha=3.5000000000000004;, score=-17.941 total time=   0.0s
[CV 1/5] END ................model__alpha=3.6;, score=-20.697 total time=   0.0s
[CV 2/5] END ................model__alpha=3.6;, score=-16.460 total time=   0.0s
[CV 3/5] END ................model__alpha=3.6;, score=-19.615 total time=   0.0s
[CV 4/5] END ................model__alpha=3.6;, score=-18.797 total time=   0.0s
[CV 5/5] END ................model__alpha=3.6;, score=-18.981 total time=   0.0s
[CV 1/5] END ................model__alpha=3.7;, score=-21.888 total time=   0.0s
[CV 2/5] END ................model__alpha=3.7;, score=-17.388 total time=   0.0s
[CV 3/5] END ................model__alpha=3.7;, score=-20.720 total time=   0.0s
[CV 4/5] END ................model__alpha=3.7;, score=-19.856 total time=   0.0s
[CV 5/5] END ................model__alpha=3.7;, score=-20.050 total time=   0.0s
[CV 1/5] END .model__alpha=3.8000000000000003;, score=-23.100 total time=   0.0s
[CV 2/5] END .model__alpha=3.8000000000000003;, score=-18.324 total time=   0.0s
[CV 3/5] END .model__alpha=3.8000000000000003;, score=-21.852 total time=   0.0s
[CV 4/5] END .model__alpha=3.8000000000000003;, score=-20.943 total time=   0.0s
[CV 5/5] END .model__alpha=3.8000000000000003;, score=-21.149 total time=   0.0s
[CV 1/5] END .model__alpha=3.9000000000000004;, score=-24.301 total time=   0.0s
[CV 2/5] END .model__alpha=3.9000000000000004;, score=-19.318 total time=   0.0s
[CV 3/5] END .model__alpha=3.9000000000000004;, score=-23.021 total time=   0.0s
[CV 4/5] END .model__alpha=3.9000000000000004;, score=-22.060 total time=   0.0s
[CV 5/5] END .model__alpha=3.9000000000000004;, score=-22.277 total time=   0.0s
[CV 1/5] END ................model__alpha=4.0;, score=-25.596 total time=   0.0s
[CV 2/5] END ................model__alpha=4.0;, score=-20.322 total time=   0.0s
[CV 3/5] END ................model__alpha=4.0;, score=-24.216 total time=   0.0s
[CV 4/5] END ................model__alpha=4.0;, score=-23.206 total time=   0.0s
[CV 5/5] END ................model__alpha=4.0;, score=-23.413 total time=   0.0s
[CV 1/5] END ................model__alpha=4.1;, score=-26.892 total time=   0.0s
[CV 2/5] END ................model__alpha=4.1;, score=-21.335 total time=   0.0s
[CV 3/5] END ................model__alpha=4.1;, score=-25.442 total time=   0.0s
[CV 4/5] END ................model__alpha=4.1;, score=-24.381 total time=   0.0s
[CV 5/5] END ................model__alpha=4.1;, score=-24.575 total time=   0.0s
[CV 1/5] END ................model__alpha=4.2;, score=-28.219 total time=   0.0s
[CV 2/5] END ................model__alpha=4.2;, score=-22.386 total time=   0.0s
[CV 3/5] END ................model__alpha=4.2;, score=-26.699 total time=   0.0s
[CV 4/5] END ................model__alpha=4.2;, score=-25.585 total time=   0.0s
[CV 5/5] END ................model__alpha=4.2;, score=-25.792 total time=   0.0s
[CV 1/5] END ................model__alpha=4.3;, score=-29.579 total time=   0.0s
[CV 2/5] END ................model__alpha=4.3;, score=-23.484 total time=   0.0s
[CV 3/5] END ................model__alpha=4.3;, score=-27.985 total time=   0.0s
[CV 4/5] END ................model__alpha=4.3;, score=-26.817 total time=   0.0s
[CV 5/5] END ................model__alpha=4.3;, score=-27.065 total time=   0.0s
[CV 1/5] END .model__alpha=4.3999999999999995;, score=-30.951 total time=   0.0s
[CV 2/5] END .model__alpha=4.3999999999999995;, score=-24.589 total time=   0.0s
[CV 3/5] END .model__alpha=4.3999999999999995;, score=-29.302 total time=   0.0s
[CV 4/5] END .model__alpha=4.3999999999999995;, score=-28.079 total time=   0.0s
[CV 5/5] END .model__alpha=4.3999999999999995;, score=-28.355 total time=   0.0s
[CV 1/5] END ................model__alpha=4.5;, score=-32.395 total time=   0.0s
[CV 2/5] END ................model__alpha=4.5;, score=-25.719 total time=   0.0s
[CV 3/5] END ................model__alpha=4.5;, score=-30.634 total time=   0.0s
[CV 4/5] END ................model__alpha=4.5;, score=-29.370 total time=   0.0s
[CV 5/5] END ................model__alpha=4.5;, score=-29.658 total time=   0.0s
[CV 1/5] END ................model__alpha=4.6;, score=-33.813 total time=   0.0s
[CV 2/5] END ................model__alpha=4.6;, score=-26.875 total time=   0.0s
[CV 3/5] END ................model__alpha=4.6;, score=-32.026 total time=   0.0s
[CV 4/5] END ................model__alpha=4.6;, score=-30.690 total time=   0.0s
[CV 5/5] END ................model__alpha=4.6;, score=-30.991 total time=   0.0s
[CV 1/5] END ................model__alpha=4.7;, score=-35.338 total time=   0.0s
[CV 2/5] END ................model__alpha=4.7;, score=-28.003 total time=   0.0s
[CV 3/5] END ................model__alpha=4.7;, score=-33.434 total time=   0.0s
[CV 4/5] END ................model__alpha=4.7;, score=-32.039 total time=   0.0s
[CV 5/5] END ................model__alpha=4.7;, score=-32.297 total time=   0.0s
[CV 1/5] END ................model__alpha=4.8;, score=-36.858 total time=   0.0s
[CV 2/5] END ................model__alpha=4.8;, score=-29.263 total time=   0.0s
[CV 3/5] END ................model__alpha=4.8;, score=-34.831 total time=   0.0s
[CV 4/5] END ................model__alpha=4.8;, score=-33.417 total time=   0.0s
[CV 5/5] END ................model__alpha=4.8;, score=-33.745 total time=   0.0s
[CV 1/5] END ................model__alpha=4.9;, score=-38.410 total time=   0.0s
[CV 2/5] END ................model__alpha=4.9;, score=-30.495 total time=   0.0s
[CV 3/5] END ................model__alpha=4.9;, score=-36.340 total time=   0.0s
[CV 4/5] END ................model__alpha=4.9;, score=-34.807 total time=   0.0s
[CV 5/5] END ................model__alpha=4.9;, score=-35.165 total time=   0.0s
[CV 1/5] END ................model__alpha=5.0;, score=-39.978 total time=   0.0s
[CV 2/5] END ................model__alpha=5.0;, score=-31.752 total time=   0.0s
[CV 3/5] END ................model__alpha=5.0;, score=-37.838 total time=   0.0s
[CV 4/5] END ................model__alpha=5.0;, score=-36.158 total time=   0.0s
[CV 5/5] END ................model__alpha=5.0;, score=-36.615 total time=   0.0s
[CV 1/5] END ................model__alpha=5.1;, score=-41.591 total time=   0.0s
[CV 2/5] END ................model__alpha=5.1;, score=-33.035 total time=   0.0s
[CV 3/5] END ................model__alpha=5.1;, score=-39.367 total time=   0.0s
[CV 4/5] END ................model__alpha=5.1;, score=-37.724 total time=   0.0s
[CV 5/5] END ................model__alpha=5.1;, score=-38.094 total time=   0.0s
[CV 1/5] END ................model__alpha=5.2;, score=-43.257 total time=   0.0s
[CV 2/5] END ................model__alpha=5.2;, score=-34.343 total time=   0.0s
[CV 3/5] END ................model__alpha=5.2;, score=-40.926 total time=   0.0s
[CV 4/5] END ................model__alpha=5.2;, score=-39.218 total time=   0.0s
[CV 5/5] END ................model__alpha=5.2;, score=-39.603 total time=   0.0s
[CV 1/5] END ................model__alpha=5.3;, score=-44.937 total time=   0.0s
[CV 2/5] END ................model__alpha=5.3;, score=-35.677 total time=   0.0s
[CV 3/5] END ................model__alpha=5.3;, score=-42.515 total time=   0.0s
[CV 4/5] END ................model__alpha=5.3;, score=-40.758 total time=   0.0s
[CV 5/5] END ................model__alpha=5.3;, score=-41.141 total time=   0.0s
[CV 1/5] END ................model__alpha=5.4;, score=-46.648 total time=   0.0s
[CV 2/5] END ................model__alpha=5.4;, score=-37.036 total time=   0.0s
[CV 3/5] END ................model__alpha=5.4;, score=-44.100 total time=   0.0s
[CV 4/5] END ................model__alpha=5.4;, score=-42.202 total time=   0.0s
[CV 5/5] END ................model__alpha=5.4;, score=-42.708 total time=   0.0s
[CV 1/5] END ................model__alpha=5.5;, score=-48.392 total time=   0.0s
[CV 2/5] END ................model__alpha=5.5;, score=-38.355 total time=   0.0s
[CV 3/5] END ................model__alpha=5.5;, score=-45.784 total time=   0.0s
[CV 4/5] END ................model__alpha=5.5;, score=-43.874 total time=   0.0s
[CV 5/5] END ................model__alpha=5.5;, score=-44.261 total time=   0.0s
[CV 1/5] END ................model__alpha=5.6;, score=-50.160 total time=   0.0s

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.249e+05, tolerance: 1.825e+05
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8,
       7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1,
       9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [30]:
search.best_params_
#We have arrived at the alpha value for the model

{'model__alpha': 0.5}

In [31]:
coefficients = search.best_estimator_.named_steps['model'].coef_

In [32]:
#Absolute value
importance = np.abs(coefficients)

In [33]:
#All the zeros here mark the columns that have least or no significance
importance

array([   0.        ,    0.        ,   37.09375732,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
        680.07721834, 1556.68163822,   36.40659707,    0.        ,
          0.        ])

In [35]:
features = x.columns

In [37]:
#The models that are actually significant.
np.array(features)[importance > 0]

array(['yr', 'casual', 'registered', 'Year'], dtype=object)

Conclusion: 'yr', 'casual', 'registered', 'Year'are the signicant varioables for the dependent variable.

In [ ]:
y_test